name: run-tests

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: python-setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
      -
        name: run-tests
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          uv run pytest tests/test_*.py -v -n auto --tb=auto
